[livekit-ai]
type=endpoint
context=xivo-extrafeatures
transport=transport-udp
allow=!all,opus,ulaw,alaw,g722
aors=livekit-ai
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
use_ptime=yes

[livekit-ai]
type=aor
contact=sip:voice_sip:5060

[emp109](+)
allow=!all,opus,ulaw,alaw,g722

[emp110](+)
allow=!all,opus,ulaw,alaw,g722

[emp101](+)
allow=!all,opus,ulaw,alaw,g722

[emp199](+)
allow=!all,opus,ulaw,alaw,g722

[emp517](+)
allow=!all,opus,ulaw,alaw,g722

[610v93lw](+)
allow=!all,opus,ulaw,alaw,g722

[3r9kqv0e](+)
allow=!all,opus,ulaw,alaw,g722

[0bqzh44e](+)
allow=!all,opus,ulaw,alaw,g722

[pg4w7jpe](+)
allow=!all,opus,ulaw,alaw,g722

[f56d5kj1](+)
allow=!all,opus,ulaw,alaw,g722

[u0ysbq1o](+)
allow=!all,opus,ulaw,alaw,g722

[wk8xmkm2](+)
allow=!all,opus,ulaw,alaw,g722

[emp155](+)
allow=!all,opus,ulaw,alaw,g722
