[livekit-ai]
type=endpoint
context=livekit-inbound
transport=transport-udp
allow=!all,ulaw,alaw
aors=livekit-ai
direct_media=no

[livekit-ai]
type=aor
contact=sip:voice_sip:5060

[livekit-ai]
type=identify
endpoint=livekit-ai
match=172.19.0.0/16,127.0.0.1

