[livekit-ai]
type=endpoint
context=xivo-extrafeatures
transport=transport-udp
allow=!all,g722,opus,ulaw,alaw
aors=livekit-ai
direct_media=no

[livekit-ai]
type=aor
contact=sip:voice_sip:5060

[emp109](+)
allow=!all,g722,opus,ulaw,alaw

[emp110](+)
allow=!all,g722,opus,ulaw,alaw

[emp101](+)
allow=!all,g722,opus,ulaw,alaw

[emp199](+)
allow=!all,g722,opus,ulaw,alaw

[emp517](+)
allow=!all,g722,opus,ulaw,alaw

[610v93lw](+)
allow=!all,g722,opus,ulaw,alaw

[3r9kqv0e](+)
allow=!all,g722,opus,ulaw,alaw

[0bqzh44e](+)
allow=!all,g722,opus,ulaw,alaw

[pg4w7jpe](+)
allow=!all,g722,opus,ulaw,alaw

[f56d5kj1](+)
allow=!all,g722,opus,ulaw,alaw

[u0ysbq1o](+)
allow=!all,g722,opus,ulaw,alaw

[wk8xmkm2](+)
allow=!all,g722,opus,ulaw,alaw
