[globals](+)
WAZO_AGID_IP = agid
LIVEKIT_SIP_ENDPOINT = 169.58.32.179:5060

[default](+)
; Route extension 999 or AI Inbound to LiveKit Voice Agent
exten => 999,1,NoOp(Forwarding to LiveKit Voice AI Agent)
same => n,Dial(PJSIP/sip:ai@${LIVEKIT_SIP_ENDPOINT},60)
same => n,Hangup()

; Queue ingress and referral landing
exten => _2XX,1,NoOp(Landing in Wazo Queue ${EXTEN})
same => n,Answer()
same => n,Queue(queue_${EXTEN},,,,300)
same => n,Hangup()

exten => _3XX,1,NoOp(Landing in Wazo Queue ${EXTEN})
same => n,Answer()
same => n,Queue(queue_${EXTEN},,,,300)
same => n,Hangup()
