# Generated by Django 5.1.15 on 2026-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الفهرسة'), ('ready', 'جاهز'), ('failed', 'فشل')], default='ready', max_length=20),
        ),
    ]
