# Generated by Django 5.1.15 on 2026-09-21 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('call_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundPBXTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='سنترال الشركة (Issabel PBX)', max_length=100)),
                ('auth_mode', models.CharField(choices=[('ip', 'IP Whitelisting (عنوان IP ثابت)'), ('credentials', 'SIP Credentials (اسم مستخدم وكلمة مرور)')], default='ip', max_length=20)),
                ('pbx_ip', models.CharField(blank=True, help_text='عنوان IP العام أو المحلي لسنترال Issabel', max_length=255, null=True)),
                ('auth_username', models.CharField(blank=True, help_text='اسم المستخدم الذي يسجل به سنترال Issabel لدينا', max_length=128, null=True)),
                ('auth_password', models.CharField(blank=True, help_text='كلمة المرور لسنترال Issabel', max_length=128, null=True)),
                ('inbound_numbers', models.CharField(blank=True, default='', help_text='أرقام الاستقبال/DIDs المسموحة مفصولة بفواصل (اختياري)', max_length=255)),
                ('destination_type', models.CharField(choices=[('ai_assistant', 'المساعد الصوتي الذكي (Smart IVR)'), ('call_queue', 'طابور انتظار محدد (Call Queue)')], default='ai_assistant', max_length=32)),
                ('livekit_trunk_id', models.CharField(blank=True, default='', help_text='معرف الجذع الوارد في LiveKit', max_length=128)),
                ('livekit_rule_id', models.CharField(blank=True, default='', help_text='معرف قاعدة التوجيه في LiveKit', max_length=128)),
                ('enable_outbound', models.BooleanField(default=True, help_text='تمكين إجراء مكالمات صادرة عبر هذا السنترال')),
                ('outbound_port', models.IntegerField(default=5060, help_text='منفذ SIP الصادر للسنترال')),
                ('outbound_transport', models.CharField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('TLS', 'TLS')], default='UDP', max_length=10)),
                ('livekit_outbound_trunk_id', models.CharField(blank=True, default='', help_text='معرف الجذع الصادر في LiveKit', max_length=128)),
                ('is_default_outbound', models.BooleanField(default=False, help_text='تعيين كجذع صادر افتراضي')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_trunks', to='agents.agentprofile')),
                ('target_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_trunks', to='call_center.callqueue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_pbx_trunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_inboundpbxtrunk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSIPTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='حساب المزود الخارجي (Generic SIP Trunk)', max_length=100)),
                ('sip_host', models.CharField(help_text='عنوان خادم المزود مثل sip.telnyx.com أو mytrunk.pstn.twilio.com', max_length=255)),
                ('sip_port', models.PositiveIntegerField(default=5060)),
                ('transport', models.CharField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('TLS', 'TLS')], default='UDP', max_length=10)),
                ('auth_username', models.CharField(blank=True, help_text='اسم المستخدم للمصادقة في المزود', max_length=128, null=True)),
                ('auth_password', models.CharField(blank=True, help_text='كلمة المرور في المزود', max_length=128, null=True)),
                ('caller_id', models.CharField(blank=True, help_text='الرقم المعتمد الذي يظهر للمتصل به بصيغة E.164', max_length=64, null=True)),
                ('livekit_outbound_trunk_id', models.CharField(blank=True, default='', help_text='معرف الجذع الصادر في LiveKit (ST_...)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_sip_trunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_outboundsiptrunk',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
