# Generated by Django 5.1.15 on 2026-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundpbxtrunk',
            name='auth_password',
            field=models.CharField(blank=True, help_text='كلمة المرور المشفرة لسنترال Issabel', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outboundsiptrunk',
            name='auth_password',
            field=models.CharField(blank=True, help_text='كلمة المرور المشفرة للمزود', max_length=255, null=True),
        ),
    ]
