# Generated by Django 5.2.17 on 2026-09-26 14:34

import django.db.models.deletion
import telephony.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_alter_inboundpbxtrunk_auth_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل جدول مواعيد العمل')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=64, verbose_name='المنطقة الزمنية')),
                ('days_config', models.JSONField(default=telephony.models.get_default_business_days_config, verbose_name='جدول الأيام وساعات العمل')),
                ('action_type', models.CharField(choices=[('ai_message', 'نطق رسالة نصية بالذكاء الاصطناعي (AI Message)'), ('audio_file', 'تشغيل ملف صوتي مسجل مسبقاً (Audio File)')], default='ai_message', max_length=20, verbose_name='إجراء خارج أوقات العمل')),
                ('ai_message', models.TextField(blank=True, default='مرحباً بك، نتأسف لاتصالك خارج أوقات العمل الرسمية. نسعد بتواصلك معنا مجدداً خلال أوقات العمل الرسمية من التاسعة صباحاً وحتى الخامسة مساءً.', verbose_name='رسالة الذكاء الاصطناعي خارج أوقات العمل')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='off_hours_audio/', verbose_name='ملف صوتي خارج أوقات العمل')),
                ('audio_file_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط الملف الصوتي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جدول مواعيد العمل',
                'verbose_name_plural': 'جداول مواعيد العمل',
                'db_table': 'voice_assistant_businesshoursschedule',
            },
        ),
    ]
