# Generated by Django 5.1.15 on 2026-10-05 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_tenantdid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTelephonyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazo_context', models.CharField(blank=True, db_index=True, default='', help_text='سياق السنترال الداخلي في Wazo', max_length=128)),
                ('wazo_context_id', models.CharField(blank=True, default='', help_text='معرف السياق في Wazo', max_length=64)),
                ('user_range_start', models.PositiveIntegerField(default=100)),
                ('user_range_end', models.PositiveIntegerField(default=899)),
                ('queue_range_start', models.PositiveIntegerField(default=200)),
                ('queue_range_end', models.PositiveIntegerField(default=299)),
                ('ai_extension', models.CharField(default='999', help_text='تحويلة الذكاء الاصطناعي الداخلية', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephony_config', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر / الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات سنترال المستأجر (Wazo Context)',
                'verbose_name_plural': 'إعدادات سنترال المستأجرين (Wazo Contexts)',
                'db_table': 'voice_assistant_tenanttelephonyconfig',
            },
        ),
    ]
