# Generated by Django 5.1.15 on 2026-09-21 23:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة / الساس')),
                ('website', models.URLField(blank=True, default='', verbose_name='موقع الساس أو الخدمة')),
                ('description', models.TextField(blank=True, default='', verbose_name='وصف النشاط وحجم الاستخدام المتوقع')),
                ('partner_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='كود الشريك')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة (Pending)'), ('approved', 'شريك معتمد (Approved)'), ('rejected', 'مرفوض (Rejected)'), ('suspended', 'موقوف مؤقتاً (Suspended)')], db_index=True, default='pending', max_length=20, verbose_name='حالة الشريك')),
                ('custom_rate_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), help_text='السعر المخفض المخصوم من محفظة الشريك لكل دقيقة محسوبة لعملائه', max_digits=10, verbose_name='سعر الدقيقة المخصص')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EGP', 'Egyptian Pound (ج.م)')], default='USD', max_length=8, verbose_name='العملة')),
                ('api_key', models.CharField(blank=True, db_index=True, max_length=80, unique=True, verbose_name='مفتاح الـ API الرئيسي')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط الـ Webhook الخاص بساس الشريك')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='مفتاح توقيع الـ Webhook (Secret)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('shared_mcp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_shared_profiles', to='agents.usermcpserver', verbose_name='خادم MCP الافتراضي لعملاء الشريك')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الشريك')),
            ],
            options={
                'verbose_name': 'ملف الشريك والـ SaaS',
                'verbose_name_plural': 'شركاء الـ SaaS (Partner Profiles)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerClientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='معرف العميل في ساس الشريك')),
                ('spending_cap', models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى للتكلفة المسموح بها لهذا العميل (فارغ = بلا سقف)', max_digits=10, null=True, verbose_name='سقف الإنفاق ($)')),
                ('minute_cap', models.PositiveIntegerField(blank=True, help_text='الحد الأقصى للدقائق الصوتية المسموح بها لهذا العميل', null=True, verbose_name='سقف الدقائق')),
                ('total_spent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='إجمالي المستهلك ($)')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي الدقائق المحتسبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل للاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_client_rel', to=settings.AUTH_USER_MODEL, verbose_name='حساب العميل')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='partners.partnerprofile', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'علاقة عميل الشريك',
                'verbose_name_plural': 'عملاء الشركاء التابعين (Sub-Clients)',
                'ordering': ['-created_at'],
            },
        ),
    ]
