# Generated by Django 5.1.15 on 2026-09-21 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='طابور المبيعات', max_length=100)),
                ('code', models.CharField(help_text='كود الطابور للاتصال والتحويل مثل 200 أو 300', max_length=32)),
                ('strategy', models.CharField(choices=[('round_robin', 'رنين بالتناوب (Round-Robin)'), ('ring_all', 'رنين جماعي متزامن (Ring-All)')], default='round_robin', max_length=32)),
                ('ring_timeout_seconds', models.PositiveIntegerField(default=15, help_text='مدة رنين الموظف قبل الانتقال للتالي')),
                ('total_timeout_seconds', models.PositiveIntegerField(default=60, help_text='أقصى مدة انتظار للعميل قبل التحويل للذكاء الاصطناعي')),
                ('hold_music', models.FileField(blank=True, help_text='ملف صوتي لموسيقى الانتظار', null=True, upload_to='hold_music/')),
                ('fallback_action', models.CharField(choices=[('ai_assistant', 'مساعد الذكاء الاصطناعي (Gemini Live)'), ('hangup', 'إنهاء المكالمة')], default='ai_assistant', max_length=32)),
                ('livekit_trunk_id', models.CharField(blank=True, max_length=128)),
                ('livekit_rule_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_callqueue',
                'ordering': ['code'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_index=True, help_text='رقم التحويلة الداخلية مثل 101 أو 102', max_length=32, unique=True)),
                ('display_name', models.CharField(default='موظف', max_length=100)),
                ('department', models.CharField(default='المبيعات', max_length=100)),
                ('status', models.CharField(choices=[('ready', 'متاح (Ready)'), ('break', 'استراحة (Break)'), ('busy', 'مشغول (Busy)'), ('offline', 'غير متصل (Offline)')], default='ready', max_length=20)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_employeeprofile',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='QueueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب أولوية الموظف في التناوب')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='call_center.employeeprofile')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='call_center.callqueue')),
            ],
            options={
                'db_table': 'voice_assistant_queuemembership',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
