# Generated by Django 5.1.15 on 2026-09-22 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='extension',
            field=models.CharField(db_index=True, help_text='رقم التحويلة الداخلية مثل 101 أو 102', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('employer', 'extension')},
        ),
    ]
