# Generated by Django 5.1.15 on 2026-09-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_employeeprofile_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_party', models.CharField(default='', help_text='اسم الطرف الثاني', max_length=200)),
                ('extension', models.CharField(default='', help_text='تحويلة أو كود الطابور', max_length=32)),
                ('room_name', models.CharField(db_index=True, default='', help_text='اسم الغرفة للربط عند الإنهاء', max_length=200)),
                ('call_type', models.CharField(choices=[('inbound', 'مكالمة واردة'), ('outbound', 'مكالمة صادرة'), ('missed', 'مكالمة فائتة'), ('transfer', 'مكالمة محولة')], default='outbound', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='call_center.employeeprofile')),
            ],
            options={
                'db_table': 'call_center_employeecalllog',
                'ordering': ['-started_at'],
            },
        ),
    ]
