# Generated by Django 5.1.15 on 2026-09-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_employeecalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='callqueue',
            name='description',
            field=models.TextField(blank=True, default='', help_text='وصف واختصاصات الطابور وتوجيهات الذكاء الاصطناعي للتحويل'),
        ),
    ]
