# Generated by Django 5.2.17 on 2026-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0004_callqueue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='push_token',
            field=models.CharField(blank=True, default='', help_text='رمز إشعارات الدفع المباشر لجهاز الموظف', max_length=255, verbose_name='Expo Push Token'),
        ),
    ]
