# Generated by Django 5.2.17 on 2026-09-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0005_employeeprofile_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecalllog',
            name='recording_url',
            field=models.CharField(blank=True, default='', help_text='رابط ملف التسجيل الصوتي MP3', max_length=500),
        ),
    ]
