# Generated by Django 5.2.17 on 2026-09-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0006_employeecalllog_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecalllog',
            name='recording_url',
            field=models.CharField(blank=True, default='', help_text='رابط ملف التسجيل الصوتي MP3', max_length=500, null=True),
        ),
    ]
