# Generated by Django 5.1.15 on 2026-09-15 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0006_usersipaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='طابور المبيعات', max_length=100)),
                ('code', models.CharField(help_text='كود الطابور للاتصال والتحويل مثل 200 أو 300', max_length=32)),
                ('strategy', models.CharField(choices=[('round_robin', 'رنين بالتناوب (Round-Robin)'), ('ring_all', 'رنين جماعي متزامن (Ring-All)')], default='round_robin', max_length=32)),
                ('ring_timeout_seconds', models.PositiveIntegerField(default=15, help_text='مدة رنين الموظف قبل الانتقال للتالي')),
                ('total_timeout_seconds', models.PositiveIntegerField(default=60, help_text='أقصى مدة انتظار للعميل قبل التحويل للذكاء الاصطناعي')),
                ('hold_music', models.FileField(blank=True, help_text='ملف صوتي لموسيقى الانتظار', null=True, upload_to='hold_music/')),
                ('fallback_action', models.CharField(choices=[('ai_assistant', 'مساعد الذكاء الاصطناعي (Gemini Live)'), ('hangup', 'إنهاء المكالمة')], default='ai_assistant', max_length=32)),
                ('livekit_trunk_id', models.CharField(blank=True, max_length=128)),
                ('livekit_rule_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QueueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب أولوية الموظف في التناوب')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='voice_assistant.callqueue')),
                ('sip_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='voice_assistant.usersipaccount')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('queue', 'sip_account')},
            },
        ),
    ]
