# Generated by Django 5.1.15 on 2026-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0007_callqueue_queuemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersipaccount',
            name='extension',
            field=models.CharField(blank=True, db_index=True, default='', help_text='رقم التحويلة المختصر مثل 1001', max_length=32),
        ),
    ]
