# Generated by Django 5.1.15 on 2026-09-16 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0008_usersipaccount_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='call_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callsession',
            name='destination_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('inbound', 'مكالمة واردة'), ('outbound_agent', 'صادرة (موظف)'), ('outbound_ai', 'صادرة (ذكاء اصطناعي)')], default='inbound', max_length=32),
        ),
        migrations.CreateModel(
            name='OutboundSIPTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='حساب المزود الخارجي (Generic SIP Trunk)', max_length=100)),
                ('sip_host', models.CharField(help_text='عنوان خادم المزود مثل sip.telnyx.com أو mytrunk.pstn.twilio.com', max_length=255)),
                ('sip_port', models.PositiveIntegerField(default=5060)),
                ('transport', models.CharField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('TLS', 'TLS')], default='UDP', max_length=10)),
                ('auth_username', models.CharField(blank=True, help_text='اسم المستخدم للمصادقة في المزود', max_length=128, null=True)),
                ('auth_password', models.CharField(blank=True, help_text='كلمة المرور في المزود', max_length=128, null=True)),
                ('caller_id', models.CharField(blank=True, help_text='الرقم المعتمد الذي يظهر للمتصل به بصيغة E.164', max_length=64, null=True)),
                ('livekit_outbound_trunk_id', models.CharField(blank=True, default='', help_text='معرف الجذع الصادر في LiveKit (ST_...)', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_sip_trunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
