# Generated by Django 5.1.15 on 2026-09-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0009_callsession_call_goal_callsession_destination_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queuemembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='queuemembership',
            name='sip_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='voice_assistant.usersipaccount'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_index=True, help_text='رقم التحويلة الداخلية مثل 101 أو 102', max_length=32, unique=True)),
                ('display_name', models.CharField(default='موظف', max_length=100)),
                ('department', models.CharField(default='المبيعات', max_length=100)),
                ('status', models.CharField(choices=[('ready', 'متاح (Ready)'), ('break', 'استراحة (Break)'), ('busy', 'مشغول (Busy)'), ('offline', 'غير متصل (Offline)')], default='ready', max_length=20)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['extension'],
            },
        ),
        migrations.AddField(
            model_name='queuemembership',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='voice_assistant.employeeprofile'),
        ),
    ]
