# Generated by Django 5.1.15 on 2026-09-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0010_alter_queuemembership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuemembership',
            name='sip_account',
        ),
        migrations.AlterField(
            model_name='queuemembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='voice_assistant.employeeprofile'),
        ),
        migrations.DeleteModel(
            name='UserSIPAccount',
        ),
    ]
