# Generated by Django 5.1.15 on 2026-09-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0012_delete_useraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callqueue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='callqueue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='queuemembership',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customermemory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='queuemembership',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='outboundsiptrunk',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermcpserver',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
        migrations.DeleteModel(
            name='CallQueue',
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
        migrations.DeleteModel(
            name='CustomerMemory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='QueueMembership',
        ),
        migrations.DeleteModel(
            name='OutboundSIPTrunk',
        ),
        migrations.DeleteModel(
            name='UserMCPServer',
        ),
    ]
