# Generated by Django 5.1.15 on 2026-09-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('inbound', 'مكالمة واردة'), ('outbound_agent', 'صادرة (موظف)'), ('outbound_ai', 'صادرة (ذكاء اصطناعي)')], default='inbound', max_length=32)),
                ('caller_phone', models.CharField(blank=True, default='', max_length=64)),
                ('destination_phone', models.CharField(blank=True, default='', max_length=64)),
                ('call_goal', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('billed_minutes', models.PositiveIntegerField(default=0, verbose_name='الدقائق المحتسبة (Ceiling)')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='تكلفة المكالمة')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_callsession',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, default='web_dashboard', max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('permanent_profile', models.JSONField(blank=True, default=dict)),
                ('last_interaction_summary', models.TextField(blank=True, default='')),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('total_calls_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_customermemory',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
