# Generated by Django 5.1.15 on 2026-09-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_systemsetting'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('call_prompt', models.TextField(blank=True, default='', verbose_name='سيناريو وهدف المكالمة المخصص (Prompt)')),
                ('max_retries', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى لمحاولات إعادة الاتصال')),
                ('retry_delay_minutes', models.PositiveIntegerField(default=15, verbose_name='المدة بالدقائق قبل إعادة المحاولة')),
                ('gateway_type', models.CharField(default='auto', max_length=32)),
                ('gateway_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة / جاهزة للاتصال'), ('running', 'قيد الاتصال الآلي'), ('paused', 'متوقف مؤقتاً'), ('completed', 'مكتملة')], default='draft', max_length=32)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('completed_contacts', models.PositiveIntegerField(default=0)),
                ('answered_contacts', models.PositiveIntegerField(default=0)),
                ('hot_leads_count', models.PositiveIntegerField(default=0)),
                ('warm_leads_count', models.PositiveIntegerField(default=0)),
                ('cold_leads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='agents.agentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حملة اتصالات صادرة',
                'verbose_name_plural': 'حملات الاتصالات الصادرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='بيانات العميل الإضافية من الملف')),
                ('call_status', models.CharField(choices=[('pending', 'جديد - في الانتظار'), ('in_progress', 'جارِ الاتصال به الآن'), ('answered', 'تم الرد والتواصل'), ('busy', 'مشغول'), ('no_answer', 'لم يرد'), ('failed', 'فشل الاتصال / غير متاح')], db_index=True, default='pending', max_length=32)),
                ('interest_level', models.CharField(choices=[('uncontacted', 'لم يتحدد بعد'), ('hot', '🔥 مهتم جداً / جاهز للمرحلة التالية'), ('warm', '🟡 مهتم / يحتاج متابعة'), ('cold', '❄️ غير مهتم / تم الرفض'), ('callback', '⏰ طلب اتصال لاحقاً'), ('unreached', '❌ تعذر الوصول إليه')], db_index=True, default='uncontacted', max_length=32)),
                ('call_summary', models.TextField(blank=True, default='')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='البيانات المستخرجة بالذكاء الاصطناعي')),
                ('retries_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contacts', to='crm.callsession')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.outboundcampaign')),
            ],
            options={
                'verbose_name': 'جهة اتصال حملة',
                'verbose_name_plural': 'جهات اتصال الحملات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserCampaignLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_calls', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للمكالمات المتزامنة')),
                ('is_auto_dialer_enabled', models.BooleanField(default=True, verbose_name='تمكين الاتصال التلقائي للحملات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حد الحملات المتزامنة للعميل',
                'verbose_name_plural': 'حدود الحملات المتزامنة للعملاء',
            },
        ),
    ]
