# Generated by Django 5.1.15 on 2026-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_outboundcampaign_campaigncontact_usercampaignlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='recording_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
