# Generated by Django 5.1.15 on 2026-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_callsession_recording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='room_name',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
