# Generated by Django 5.1.15 on 2026-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_callsession_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='caller_extension',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='تحويلة الموظف المتصل'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='is_internal_test',
            field=models.BooleanField(default=False, verbose_name='مكالمة اختبار داخلية لموظف'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('inbound', 'مكالمة واردة'), ('outbound_agent', 'صادرة (موظف)'), ('outbound_ai', 'صادرة (ذكاء اصطناعي)'), ('internal_test', 'مكالمة اختبار داخلية (Internal Test)')], default='inbound', max_length=32),
        ),
    ]
