# Generated by Django 5.1.15 on 2026-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_callsession_caller_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='direction',
            field=models.CharField(choices=[('inbound', 'مكالمة واردة'), ('outbound_agent', 'صادرة (موظف)'), ('outbound_ai', 'صادرة (ذكاء اصطناعي)'), ('internal_test', 'مكالمة اختبار داخلية (Internal Test)'), ('internal_employee', 'مكالمة داخلية (موظفين / سنترال)')], default='inbound', max_length=32),
        ),
    ]
