# Generated by Django 5.1.15 on 2026-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_callsession_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='transferred_recording_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='تسجيل مكالمة الموظف البشري المحولة'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='transferred_to_extension',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='التحويلة أو الطابور المحول إليه'),
        ),
    ]
