# Generated by Django 5.1.15 on 2026-10-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_callsession_transferred_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemory',
            name='call_memory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customermemory',
            name='whatsapp_memory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='OmnichannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(default='whatsapp', max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'وارد من العميل'), ('outbound_ai', 'صادر من الذكاء الاصطناعي'), ('outbound_human', 'صادر من موظف بشري')], default='outbound_ai', max_length=20)),
                ('message_text', models.TextField()),
                ('is_followup', models.BooleanField(default=False)),
                ('followup_reason', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnichannel_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
