# Generated by Django 5.1.15 on 2026-10-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_callsession_transferred_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=64, verbose_name='نوع الإجراء (Action Type)')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='تفاصيل القرار ومبرراته')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات التنفيذ البرمجية (Payload)')),
                ('status', models.CharField(choices=[('pending', 'قيد انتظار الموافقة (Pending)'), ('approved', 'تمت الموافقة (Approved)'), ('rejected', 'مرفوض (Rejected)'), ('executed', 'تم التنفيذ بنجاح (Executed)'), ('failed', 'فشل التنفيذ (Failed)')], db_index=True, default='pending', max_length=32, verbose_name='حالة الطلب')),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=128, verbose_name='معرف رسالة تيليجرام')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف شات تيليجرام')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('decision_reason', models.TextField(blank=True, default='', verbose_name='ملاحظات المعتمد')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='نتيجة التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='crm.customermemory', verbose_name='العميل المعني')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر / الشركة')),
            ],
            options={
                'verbose_name': 'طلب موافقة مشروطة',
                'verbose_name_plural': 'بوابات الموافقة الذكية (Approval Gates)',
                'db_table': 'crm_approvalrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmnichannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب (WhatsApp)'), ('telegram', 'تيليجرام (Telegram)'), ('email', 'بريد إلكتروني (Email)'), ('phone', 'مكالمة هاتفية (Phone)')], db_index=True, max_length=32, verbose_name='القناة')),
                ('direction', models.CharField(choices=[('inbound', 'وارد (Inbound)'), ('outbound', 'صادر (Outbound)')], default='outbound', max_length=16, verbose_name='الاتجاه')),
                ('sender', models.CharField(default='', max_length=255, verbose_name='المرسل')),
                ('recipient', models.CharField(default='', max_length=255, verbose_name='المستلم')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات وصفية')),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('delivered', 'تم التوصيل'), ('read', 'تمت القراءة'), ('failed', 'فشل')], default='delivered', max_length=32, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omnichannel_messages', to='crm.customermemory', verbose_name='ذاكرة العميل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnichannel_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر / الشركة')),
            ],
            options={
                'verbose_name': 'رسالة متعددة القنوات',
                'verbose_name_plural': 'سجل رسائل القنوات الشاملة (Omnichannel Messages)',
                'db_table': 'crm_omnichannelmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerChannelIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب (WhatsApp)'), ('telegram', 'تيليجرام (Telegram)'), ('email', 'بريد إلكتروني (Email)')], db_index=True, max_length=32, verbose_name='قناة التواصل')),
                ('identifier', models.CharField(db_index=True, max_length=255, verbose_name='المعرف (رقم/إيميل/Chat ID)')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تم التحقق منه')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_identifiers', to='crm.customermemory', verbose_name='ذاكرة العميل')),
            ],
            options={
                'verbose_name': 'معرف قناة العميل',
                'verbose_name_plural': 'معرفات قنوات العملاء (Omnichannel Identifiers)',
                'db_table': 'crm_customerchannelidentifier',
                'unique_together': {('customer_memory', 'channel', 'identifier')},
            },
        ),
    ]
