# Generated by Django 5.1.15 on 2026-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customermemory_call_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermemory',
            name='phone_number',
            field=models.CharField(db_index=True, default='web_dashboard', max_length=64),
        ),
        migrations.AlterField(
            model_name='omnichannelmessage',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
