# Generated by Django 5.1.15 on 2026-10-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_customermemory_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboundcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'حملة اتصالات وتسويق صادر', 'verbose_name_plural': 'حملات الاتصالات والتسويق الصادر'},
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='whatsapp_message_text',
            field=models.TextField(blank=True, default='', verbose_name='رسالة الواتساب المرسلة'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='whatsapp_status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('in_progress', 'جارِ الإرسال'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('replied', 'تم الرد والتفاعل'), ('failed', 'فشل الإرسال'), ('skipped', 'تم التخطي')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='channel',
            field=models.CharField(choices=[('calls', 'مكالمات فقط'), ('whatsapp', 'واتساب فقط'), ('hybrid', 'هجينة (مكالمات + واتساب)')], default='calls', max_length=32, verbose_name='قناة الحملة'),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='whatsapp_prompt',
            field=models.TextField(blank=True, default='', verbose_name='سيناريو ورسالة الواتساب المخصصة (WhatsApp Prompt)'),
        ),
        migrations.AddField(
            model_name='outboundcampaign',
            name='whatsapp_sent_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outboundcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة / جاهزة للاتصال'), ('running', 'قيد التنفيذ الآلي'), ('paused', 'متوقف مؤقتاً'), ('completed', 'مكتملة')], default='draft', max_length=32),
        ),
    ]
