# Generated by Django 5.1.15 on 2026-09-21 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='البروفايل الافتراضي', max_length=100)),
                ('voice_name', models.CharField(default='Aoede', max_length=50)),
                ('gender', models.CharField(choices=[('female', 'أنثى'), ('male', 'ذكر')], default='female', max_length=20)),
                ('dialect', models.CharField(choices=[('egyptian', 'لهجة مصرية عامية'), ('saudi', 'لهجة خليجية / سعودية'), ('levantine', 'لهجة شامية'), ('fusha', 'عربية فصحى معاصرة'), ('english', 'English')], default='egyptian', max_length=50)),
                ('persona_role', models.CharField(choices=[('customer_support', 'خدمة عملاء ومبيعات المتجر'), ('sales_advisor', 'مستشار تسويق ومبيعات شاطر'), ('personal_assistant', 'مساعد شخصي ذكي وودود'), ('technical_consultant', 'مستشار فني ورسمي')], default='customer_support', max_length=50)),
                ('speaking_style', models.CharField(choices=[('friendly', 'ودود ولطيف ومرح'), ('formal', 'رسمي وهادئ ورصين'), ('concise', 'مباشر وسريع وموجز'), ('enthusiastic', 'حماسي وتشجيعي')], default='friendly', max_length=50)),
                ('custom_instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_agentprofile',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='خادم المتجر الرئيسي (FastMCP)', max_length=100)),
                ('server_url', models.CharField(default='http://mock-store:8002/sse', max_length=500)),
                ('auth_token', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('cached_tools', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_assistant_usermcpserver',
                'ordering': ['-updated_at'],
            },
        ),
    ]
