# Generated by Django 5.1.15 on 2026-09-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='language',
            field=models.CharField(choices=[('arabic', 'العربية (Arabic)'), ('english', 'English'), ('french', 'Français (French)'), ('spanish', 'Español (Spanish)'), ('german', 'Deutsch (German)'), ('italian', 'Italiano (Italian)'), ('turkish', 'Türkçe (Turkish)'), ('russian', 'Русский (Russian)'), ('urdu', 'اردو (Urdu)'), ('hindi', 'हिन्दी (Hindi)'), ('chinese', '中文 (Mandarin Chinese)')], default='arabic', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='dialect',
            field=models.CharField(choices=[('egyptian', 'لهجة مصرية عامية (مصر)'), ('saudi', 'لهجة سعودية / نجدية وحجازية (السعودية)'), ('emirati', 'لهجة إماراتية / خليجية (الإمارات)'), ('kuwaiti', 'لهجة كويتية (الكويت)'), ('levantine', 'لهجة شامية (سوريا ولبنان)'), ('jordanian_palestinian', 'لهجة أردنية وفلسطينية (الأردن وفلسطين)'), ('moroccan', 'لهجة مغربية / دارجة (المغرب)'), ('algerian', 'لهجة جزائرية (الجزائر)'), ('tunisian', 'لهجة تونسية (تونس)'), ('iraqi', 'لهجة عراقية (العراق)'), ('sudanese', 'لهجة سودانية (السودان)'), ('yemeni', 'لهجة يمنية (اليمن)'), ('fusha', 'عربية فصحى معاصرة (رسمية)'), ('english_us', 'American English (US)'), ('english_uk', 'British English (UK)'), ('english_aus', 'Australian English (Australia)'), ('english_ind', 'Indian English (India)'), ('english', 'General English'), ('french_fr', 'Français Métropolitain (France)'), ('french_ca', 'Français Canadien (Canada)'), ('spanish_es', 'Español de España (Spain)'), ('spanish_latam', 'Español Latinoamericano'), ('german_de', 'Standarddeutsch (Germany & Austria)'), ('italian_it', 'Italiano Standard (Italy)'), ('turkish_tr', 'Türkçe (Turkey)'), ('russian_ru', 'Русский язык (Russia)'), ('urdu_pk', 'اردو (Pakistan & India)'), ('hindi_in', 'हिन्दी (India)'), ('chinese_zh', '普通话 (Mandarin Chinese)')], default='egyptian', max_length=50),
        ),
    ]
