# Generated by Django 5.1.15 on 2026-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentprofile_language_alter_agentprofile_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='persona_role',
            field=models.TextField(blank=True, default='خدمة عملاء ومبيعات المتجر'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='speaking_style',
            field=models.TextField(blank=True, default='ودود ولطيف ومرح'),
        ),
    ]
