# Generated by Django 5.1.15 on 2026-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentprofile_persona_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='verbosity',
            field=models.CharField(choices=[('concise', 'مختصر (ردود سريعة ومباشرة في 1-2 جملة)'), ('balanced', 'متوازن (طبيعي ومهذب في 2-3 جمل)'), ('detailed', 'مفصل (شرح وافٍ واستشاري)')], default='balanced', max_length=20),
        ),
    ]
