# Generated by Django 5.2.17 on 2026-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentprofile_verbosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='welcome_message',
            field=models.TextField(blank=True, default='', help_text='الرسالة الترحيبية التي يبدأ بها المساعد فور فتح المكالمة (مثال: أهلاً بك، معك أحمد، كيف أقدر أساعدك؟)', verbose_name='رسالة الترحيب الافتتاحية'),
        ),
    ]
