# Generated by Django 5.2.17 on 2026-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentprofile_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_welcome_message_enabled',
            field=models.BooleanField(default=True, help_text='تفعيل أو إيقاف الترحيب التلقائي عند بدء المكالمة. عند التعطيل، ينتظر المساعد حتى يتحدث المتصل أولاً.', verbose_name='تفعيل رسالة الترحيب الافتتاحية'),
        ),
    ]
