# Generated by Django 5.2.17 on 2026-09-27 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentprofile_is_welcome_message_enabled'),
        ('crm', '0004_alter_callsession_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=120, verbose_name='معرف الغرفة')),
                ('caller_phone', models.CharField(blank=True, default='', max_length=64, verbose_name='رقم المتصل')),
                ('tool_name', models.CharField(db_index=True, max_length=100, verbose_name='اسم الأداة')),
                ('tool_type', models.CharField(choices=[('mcp', 'خادم أدوات خارجي (FastMCP)'), ('rag', 'بحث المستندات (RAG)'), ('memory', 'ذاكرة العملاء (CRM Memory)'), ('transfer', 'تحويل طابور (Queue Transfer)')], default='mcp', max_length=30, verbose_name='نوع الأداة')),
                ('server_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم السيرفر / النظام')),
                ('server_url', models.CharField(blank=True, default='', max_length=500, verbose_name='رابط الخادم')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='مدخلات الأداة (Arguments)')),
                ('status', models.CharField(choices=[('success', 'ناجح (Success)'), ('failed', 'فشل أداة (Tool Error)'), ('timeout', 'انتهاء المهلة (Timeout)'), ('connection_error', 'فشل اتصال (Connection Error)'), ('validation_error', 'خطأ تحقق (Validation Error)')], db_index=True, default='success', max_length=30, verbose_name='حالة التنفيذ')),
                ('error_type', models.CharField(blank=True, default='none', max_length=50, verbose_name='نوع الخطأ')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='سبب ورسالة الخطأ')),
                ('response_preview', models.TextField(blank=True, default='', verbose_name='معاينة الرد')),
                ('raw_response', models.JSONField(blank=True, default=dict, null=True, verbose_name='الرد الكامل (JSON)')),
                ('execution_time_ms', models.IntegerField(default=0, verbose_name='مدة التنفيذ (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الاستدعاء')),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_call_logs', to='crm.callsession', verbose_name='جلسة المكالمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_call_logs', to=settings.AUTH_USER_MODEL, verbose_name='العميل / الشركة')),
            ],
            options={
                'verbose_name': 'سجل استدعاء الأداة',
                'verbose_name_plural': 'مراقبة استدعاءات الأدوات (Tool Logs)',
                'db_table': 'voice_assistant_agenttoolcalllog',
                'ordering': ['-created_at'],
            },
        ),
    ]
