# Generated by Django 5.2.17 on 2026-09-27 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agenttoolcalllog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLiveContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='البيانات المنظمة اللحظية (Structured JSON)')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='حجم البيانات (بايت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_context', to=settings.AUTH_USER_MODEL, verbose_name='العميل / الشركة')),
            ],
            options={
                'verbose_name': 'الذاكرة المنظمة الحية (Live Context)',
                'verbose_name_plural': 'الذاكرة المنظمة الحية (Live Contexts)',
                'db_table': 'voice_assistant_tenantlivecontext',
            },
        ),
    ]
