# Generated by Django 5.1.15 on 2026-10-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentprofile_off_topic_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCoworkerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_mode', models.CharField(choices=[('call_center_only', 'كول سنتر ذكي فقط (Smart Call Center Only)'), ('digital_coworker', 'موظف رقمي ذكي شامل (Autonomous Digital Coworker)')], default='call_center_only', max_length=32, verbose_name='نمط الخدمة')),
                ('coworker_name', models.CharField(default='المساعد الرقمي الذكي', max_length=100, verbose_name='اسم الموظف الذكي')),
                ('coworker_role', models.CharField(choices=[('sdr', 'موظف مبيعات وتأهيل عملاء (AI SDR & Sales Development)'), ('support', 'موظف دعم وعمليات ولوجستيات (Operations & Support)'), ('collections', 'موظف تحصيل ومتابعات مالية (Collections & Retention)'), ('executive_assistant', 'مساعد تنفيذي وإداري شامل (Executive Assistant)'), ('custom', 'دور مخصص (Custom Role)')], default='sdr', max_length=32, verbose_name='الدور الوظيفي')),
                ('autonomy_level', models.CharField(choices=[('conditional_approval', 'استقلالية ذكية مع بوابات موافقة (Conditional Approval Gates)'), ('full_autonomy', 'استقلالية كاملة مع قيود صارمة (Full Autonomy with Strict Budget)'), ('draft_first', 'نمط المسودة الدائمة (Draft-First Mode)')], default='conditional_approval', max_length=32, verbose_name='مستوى الاستقلالية')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=200, verbose_name='رمز توكن بوت تيليجرام')),
                ('telegram_manager_chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف شات المدير (Chat ID)')),
                ('whatsapp_mode', models.CharField(choices=[('meta_cloud', 'Meta Cloud API (الربط الرسمي للشركات)'), ('qr_code', 'محرك مسح QR Code (Evolution API / Baileys)')], default='meta_cloud', max_length=32, verbose_name='مزود خدمة الواتساب')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Phone Number ID (Meta)')),
                ('whatsapp_access_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Access Token (Meta)')),
                ('whatsapp_instance_name', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم الجلسة / Instance (QR)')),
                ('whatsapp_qr_code', models.TextField(blank=True, default='', verbose_name='كود QR اللحظي للمسح')),
                ('is_whatsapp_connected', models.BooleanField(default=False, verbose_name='حالة اتصال الواتساب')),
                ('email_followups_enabled', models.BooleanField(default=True, verbose_name='تمكين المتابعة بالبريد الإلكتروني')),
                ('email_sender_name', models.CharField(blank=True, default='', max_length=120, verbose_name='اسم المرسل في الإيميل')),
                ('auto_call_followup_enabled', models.BooleanField(default=True, verbose_name='تمكين الموظف من إجراء مكالمات متابعة ذاتية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_config', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر / الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات الموظف الذكي الشامل',
                'verbose_name_plural': 'إعدادات الموظفين الأذكياء (Digital Coworkers)',
            },
        ),
    ]
