# Generated by Django 5.1.15 on 2026-10-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_digitalcoworkerconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcoworkerconfig',
            name='autonomy_level',
            field=models.CharField(blank=True, default='conditional_approval', max_length=64, verbose_name='مستوى الاستقلالية'),
        ),
        migrations.AlterField(
            model_name='digitalcoworkerconfig',
            name='coworker_role',
            field=models.CharField(blank=True, default='sdr', max_length=120, verbose_name='الدور الوظيفي'),
        ),
    ]
