# Generated by Django 5.1.15 on 2026-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_digitalcoworkerconfig_autonomy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='approval_rules',
            field=models.JSONField(blank=True, default=list, verbose_name='قواعد بوابات الموافقة المشروطة'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='auto_whatsapp_followup_enabled',
            field=models.BooleanField(default=True, verbose_name='تمكين المتابعة بالواتساب تلقائياً'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='custom_instructions',
            field=models.TextField(blank=True, default='', verbose_name='تعليمات السلوك المستقل'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='email_from_address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان البريد الإلكتروني للمرسل'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='حالة تفعيل الموظف الذكي'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='proactive_actions_enabled',
            field=models.BooleanField(default=True, verbose_name='تمكين الإجراءات الاستباقية'),
        ),
    ]
