# Generated by Django 5.1.15 on 2026-10-09 01:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_digitalcoworkerconfig_approval_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworker_configs', to='agents.agentprofile', verbose_name='الشخصية الصوتية للموظف الذكي'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='daily_calls_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='الحد الأقصى للمكالمات اليومية'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='max_budget_per_day',
            field=models.DecimalField(decimal_places=4, default=Decimal('50.00'), max_digits=10, verbose_name='الحد الأقصى للإنفاق اليومي ($)'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='whatsapp_evolution_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح API لخادم Evolution'),
        ),
        migrations.AddField(
            model_name='digitalcoworkerconfig',
            name='whatsapp_evolution_api_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رابط خادم Evolution API'),
        ),
    ]
