# Generated by Django 5.1.15 on 2026-09-21 22:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='التكلفة المخصومة لكل دقيقة مكالمة محسوبة', max_digits=10, verbose_name='سعر الدقيقة')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EGP', 'Egyptian Pound (ج.م)')], default='USD', help_text='العملة المعتمدة لحساب الرصيد والخصم (دولار أو مصري)', max_length=8, verbose_name='العملة')),
                ('rounding_mode', models.CharField(choices=[('ceil', 'تقريب لأعلى دقيقة كاملة (Ceiling - أي ثانية تُحسب دقيقة)')], default='ceil', help_text='التقريب الصارم لأقرب دقيقة مرتفع: 61 ثانية = دقيقتان', max_length=16, verbose_name='طريقة احتساب الدقائق')),
                ('min_balance_to_call', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='الحد الأدنى للرصيد المطلوب لبدء أي مكالمة صوتية جديدة', max_digits=10, verbose_name='الحد الأدنى لبدء مكالمة')),
                ('initial_welcome_credit', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), help_text='الرصيد المبدئي المجاني الممنوح للمستخدم الجديد للتجربة', max_digits=10, verbose_name='رصيد ترحيبي تجريبي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات التسعير والفواتير',
                'verbose_name_plural': 'إعدادات التسعير والفواتير',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=12, verbose_name='الرصيد المتاح')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='العملة')),
                ('total_spent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='إجمالي المستهلك')),
                ('total_deposited', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=12, verbose_name='إجمالي المشحون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة رصيد العميل',
                'verbose_name_plural': 'محافظ رصيد العملاء',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('call_deduction', 'خصم مكالمة صوتية'), ('topup', 'شحن رصيد مباشر'), ('admin_adjustment', 'تعديل رصيد إداري'), ('welcome_bonus', 'رصيد ترحيبي مجاني')], default='call_deduction', max_length=32, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=4, help_text='موجب للشحن وسالب للخصم', max_digits=12, verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الرصيد بعد الحركة')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='العملة')),
                ('actual_seconds', models.PositiveIntegerField(default=0, verbose_name='الثواني الفعلية')),
                ('billed_minutes', models.PositiveIntegerField(default=0, verbose_name='الدقائق المحتسبة (Ceiling)')),
                ('rate_applied', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='السعر المطبق للدقيقة')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف والبيان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='crm.callsession', verbose_name='جلسة المكالمة المرتبطة')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.userwallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'سجل الحركات المالية (Ledger)',
                'ordering': ['-created_at'],
            },
        ),
    ]
